version: '3.8'

services:
  postgres:
    image: postgres:14.1
    env_file:
      - .env.test
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: redis:7.0.7
    env_file:
      - .env.test
    ports:
      - "${REDIS_PORT}:6379"